export { PrivateRoutes } from './PrivateRoutes/privateRoutes';
export { Header } from './Header';
export { Footer } from './Footer';
export { SkeletonProducts } from './SkeletonProducts';
export { Product } from './Product';
export { LoginAndRegister } from './LoginAndRegister';
export { LoadingUser } from './LoadingUser/loadingUser';
export { CountManyItems } from './CountManyItems/countManyItems';
export { ManagerContain } from './ManagerContain/managerContain';
